/*
 * Receptkezelő webalkalmazás Api
 *
 * TODO
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using WencyFyre.RecipeApp.Backend.Api.Attributes;
using WencyFyre.RecipeApp.Backend.Api.Models;

namespace WencyFyre.RecipeApp.Backend.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class RecipesApiController : ControllerBase
    { 
        /// <summary>
        /// Creates a recipe
        /// </summary>
        /// <response code="201">Recipe created successfully</response>
        [HttpPost]
        [Route("/recipes/")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 201, type: typeof(CreateRecipeDTO))]
        public abstract IActionResult CreateRecipe();
    }
}
