name: ${APP_NAME}
services:
  proxy:
    image: ghcr.io/wemcy/recipe-app-proxy
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:  
      PUBLIC_HOST: ${APP_HOST}
      PUBLIC_PORT: ${APP_PORT}
      PROXY_TLS_ENABLED: ${PROXY_TLS_ENABLED:-false}
      PROXY_TLS_CERTIFICATE_FILE: ${PROXY_TLS_CERTIFICATE_FILE:-tls.crt}
      PROXY_TLS_CERTIFICATE_KEY_FILE: ${PROXY_TLS_CERTIFICATE_KEY_FILE:-tls.key}
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 80
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
    volumes:
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
  frontend:
    image: ghcr.io/wemcy/recipe-app-frontend

  backend:
    image: ghcr.io/wemcy/recipe-app-backend
    user: root
    depends_on:
      recipe_database:
        condition: service_healthy
    environment:
      ConnectionStrings__Default: "Host=recipe_database;Port=5432;Database=recipe-app;Username=${DATABASE_USERNAME};Password=${DATABASE_PASSWORD}"
      Admin__Email: ${ADMIN_EMAIL}
      Admin__Password: ${ADMIN_DEFAULT_PASSWORD}
      Cors__AllowedOrigins__0: "${APP_HOST}:${APP_PORT}"
      Cors__AllowedOrigins__1: "http://${APP_HOST}:${APP_PORT}"
      Cors__AllowedOrigins__2: "http://${APP_HOST}"
      Cors__AllowedOrigins__3: "https://${APP_HOST}:${APP_PORT}"
      Cors__AllowedOrigins__4: "https://${APP_HOST}"
      ImageSizes__Thumbnail__Width: ${SIZE_OPTION_THUMBNAIL_WIDTH}
      ImageSizes__Thumbnail__Height: ${SIZE_OPTION_THUMBNAIL_HEIGHT}
      ImageSizes__Medium__Width: ${SIZE_OPTION_MEDIUM_WIDTH}
      ImageSizes__Medium__Height: ${SIZE_OPTION_MEDIUM_HEIGHT}
      ImageSizes__Large__Width: ${SIZE_OPTION_LARGE_WIDTH}
      ImageSizes__Large__Height: ${SIZE_OPTION_LARGE_HEIGHT}
      Pagination__DefaultPageSize: ${PAGINATION_DEFAULT_PAGE_SIZE}
    volumes:
      - recipe_images:/storage/recipe_images

  recipe_database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: recipe-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 12
    volumes:
      - recipe_db_data:/var/lib/postgresql/data


volumes:
  recipe_db_data:
  recipe_images:
