/*
 * Recipe Management Web Application API
 *
 * Recipe create/list/update/delete operations with allergen-based filtering.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Wemcy.RecipeApp.Backend.Api.Converters;

namespace Wemcy.RecipeApp.Backend.Api.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class CreateIngredientSuggestionRequest : IEquatable<CreateIngredientSuggestionRequest>
    {
        /// <summary>
        /// The name of the ingredient
        /// </summary>
        /// <value>The name of the ingredient</value>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// List of allergens present in the recipe
        /// </summary>
        /// <value>List of allergens present in the recipe</value>
        [Required]
        [DataMember(Name="allergens", EmitDefaultValue=false)]
        public List<Allergen> Allergens { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateIngredientSuggestionRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Allergens: ").Append(Allergens).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateIngredientSuggestionRequest)obj);
        }

        /// <summary>
        /// Returns true if CreateIngredientSuggestionRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateIngredientSuggestionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateIngredientSuggestionRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Allergens == other.Allergens ||
                    Allergens != null &&
                    other.Allergens != null &&
                    Allergens.SequenceEqual(other.Allergens)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Allergens != null)
                    hashCode = hashCode * 59 + Allergens.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateIngredientSuggestionRequest left, CreateIngredientSuggestionRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateIngredientSuggestionRequest left, CreateIngredientSuggestionRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
