/*
 * Receptkezelő webalkalmazás API
 *
 * Recepthozzáadás, -listázás, -szerkesztés, -törlés; allergén-alapú szűréssel.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Wemcy.RecipeApp.Backend.Api.Converters;

namespace Wemcy.RecipeApp.Backend.Api.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class CreateRecipeDTO : IEquatable<CreateRecipeDTO>
    {
        /// <summary>
        /// The title of the new recipe
        /// </summary>
        /// <value>The title of the new recipe</value>
        [Required]
        [MinLength(1)]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Simple description of the recipe
        /// </summary>
        /// <value>Simple description of the recipe</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// List of allergens present in the recipe
        /// </summary>
        /// <value>List of allergens present in the recipe</value>
        /* <example>[1,3,5]</example> */
        [DataMember(Name="allergens", EmitDefaultValue=false)]
        public List<Allergen> Allergens { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateRecipeDTO {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Allergens: ").Append(Allergens).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateRecipeDTO)obj);
        }

        /// <summary>
        /// Returns true if CreateRecipeDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateRecipeDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateRecipeDTO other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    Allergens == other.Allergens ||
                    Allergens != null &&
                    other.Allergens != null &&
                    Allergens.SequenceEqual(other.Allergens)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (Allergens != null)
                    hashCode = hashCode * 59 + Allergens.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateRecipeDTO left, CreateRecipeDTO right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateRecipeDTO left, CreateRecipeDTO right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
