/*
 * Recipe Management Web Application API
 *
 * Recipe create/list/update/delete operations with allergen-based filtering.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Wemcy.RecipeApp.Backend.Api.Converters;

namespace Wemcy.RecipeApp.Backend.Api.Models
{ 
        /// <summary>
        /// Gets or Sets ImageSize
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ImageSize>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ImageSize
        {
            
            /// <summary>
            /// Enum ThumbnailEnum for thumbnail
            /// </summary>
            [EnumMember(Value = "thumbnail")]
            ThumbnailEnum = 1,
            
            /// <summary>
            /// Enum MediumEnum for medium
            /// </summary>
            [EnumMember(Value = "medium")]
            MediumEnum = 2,
            
            /// <summary>
            /// Enum LargeEnum for large
            /// </summary>
            [EnumMember(Value = "large")]
            LargeEnum = 3
        }
}
