/*
 * Recipe Management Web Application API
 *
 * Recipe create/list/update/delete operations with allergen-based filtering.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Wemcy.RecipeApp.Backend.Api.Converters;

namespace Wemcy.RecipeApp.Backend.Api.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class PaginationMetadata : IEquatable<PaginationMetadata>
    {
        /// <summary>
        /// Total number of items available
        /// </summary>
        /// <value>Total number of items available</value>
        [DataMember(Name="totalCount", EmitDefaultValue=true)]
        public int? TotalCount { get; set; }

        /// <summary>
        /// Current page number (starting from 0)
        /// </summary>
        /// <value>Current page number (starting from 0)</value>
        [DataMember(Name="pageNumber", EmitDefaultValue=true)]
        public int? PageNumber { get; set; }

        /// <summary>
        /// Current page number (starting from 0)
        /// </summary>
        /// <value>Current page number (starting from 0)</value>
        [DataMember(Name="currentPage", EmitDefaultValue=true)]
        public int? CurrentPage { get; set; }

        /// <summary>
        /// Number of items per page
        /// </summary>
        /// <value>Number of items per page</value>
        [DataMember(Name="pageSize", EmitDefaultValue=true)]
        public int? PageSize { get; set; }

        /// <summary>
        /// Indicates if there is a next page available
        /// </summary>
        /// <value>Indicates if there is a next page available</value>
        [DataMember(Name="hasNextPage", EmitDefaultValue=true)]
        public bool? HasNextPage { get; set; }

        /// <summary>
        /// Indicates if there is a previous page available
        /// </summary>
        /// <value>Indicates if there is a previous page available</value>
        [DataMember(Name="hasPreviousPage", EmitDefaultValue=true)]
        public bool? HasPreviousPage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaginationMetadata {\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  PageNumber: ").Append(PageNumber).Append("\n");
            sb.Append("  CurrentPage: ").Append(CurrentPage).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  HasNextPage: ").Append(HasNextPage).Append("\n");
            sb.Append("  HasPreviousPage: ").Append(HasPreviousPage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaginationMetadata)obj);
        }

        /// <summary>
        /// Returns true if PaginationMetadata instances are equal
        /// </summary>
        /// <param name="other">Instance of PaginationMetadata to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaginationMetadata other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TotalCount == other.TotalCount ||
                    
                    TotalCount.Equals(other.TotalCount)
                ) && 
                (
                    PageNumber == other.PageNumber ||
                    
                    PageNumber.Equals(other.PageNumber)
                ) && 
                (
                    CurrentPage == other.CurrentPage ||
                    
                    CurrentPage.Equals(other.CurrentPage)
                ) && 
                (
                    PageSize == other.PageSize ||
                    
                    PageSize.Equals(other.PageSize)
                ) && 
                (
                    HasNextPage == other.HasNextPage ||
                    
                    HasNextPage.Equals(other.HasNextPage)
                ) && 
                (
                    HasPreviousPage == other.HasPreviousPage ||
                    
                    HasPreviousPage.Equals(other.HasPreviousPage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + TotalCount.GetHashCode();
                    
                    hashCode = hashCode * 59 + PageNumber.GetHashCode();
                    
                    hashCode = hashCode * 59 + CurrentPage.GetHashCode();
                    
                    hashCode = hashCode * 59 + PageSize.GetHashCode();
                    
                    hashCode = hashCode * 59 + HasNextPage.GetHashCode();
                    
                    hashCode = hashCode * 59 + HasPreviousPage.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaginationMetadata left, PaginationMetadata right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaginationMetadata left, PaginationMetadata right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
