/*
 * Receptkezelő webalkalmazás API
 *
 * Recepthozzáadás, -listázás, -szerkesztés, -törlés; allergén-alapú szűréssel.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Wemcy.RecipeApp.Backend.Api.Converters;

namespace Wemcy.RecipeApp.Backend.Api.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class ProfileResponse : IEquatable<ProfileResponse>
    {
        /// <summary>
        /// A bejelentkezett felhasználó azonosítója
        /// </summary>
        /// <value>A bejelentkezett felhasználó azonosítója</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [Required]
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// A bejelentkezett felhasználó megjelenítendő neve
        /// </summary>
        /// <value>A bejelentkezett felhasználó megjelenítendő neve</value>
        [Required]
        [DataMember(Name="displayName", EmitDefaultValue=false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// A bejelentkezett felhasználó regisztrációjának időpontja
        /// </summary>
        /// <value>A bejelentkezett felhasználó regisztrációjának időpontja</value>
        [Required]
        [DataMember(Name="registeredAt", EmitDefaultValue=true)]
        public DateTimeOffset RegisteredAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProfileResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  RegisteredAt: ").Append(RegisteredAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProfileResponse)obj);
        }

        /// <summary>
        /// Returns true if ProfileResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ProfileResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProfileResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    Email == other.Email ||
                    Email != null &&
                    Email.Equals(other.Email)
                ) && 
                (
                    DisplayName == other.DisplayName ||
                    DisplayName != null &&
                    DisplayName.Equals(other.DisplayName)
                ) && 
                (
                    RegisteredAt == other.RegisteredAt ||
                    
                    RegisteredAt.Equals(other.RegisteredAt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Email != null)
                    hashCode = hashCode * 59 + Email.GetHashCode();
                    if (DisplayName != null)
                    hashCode = hashCode * 59 + DisplayName.GetHashCode();
                    
                    hashCode = hashCode * 59 + RegisteredAt.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProfileResponse left, ProfileResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProfileResponse left, ProfileResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
