/*
 * Receptkezelő webalkalmazás API
 *
 * Recepthozzáadás, -listázás, -szerkesztés, -törlés; allergén-alapú szűréssel.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Wemcy.RecipeApp.Backend.Api.Converters;

namespace Wemcy.RecipeApp.Backend.Api.Models
{ 
        /// <summary>
        /// List of roles to assign to the user (e.g., [\"User\"] or [\"Admin\"])
        /// </summary>
        /// <value>List of roles to assign to the user (e.g., [\"User\"] or [\"Admin\"])</value>
        [TypeConverter(typeof(CustomEnumConverter<RolesEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum RolesEnum
        {
            
            /// <summary>
            /// Enum AdminEnum for Admin
            /// </summary>
            [EnumMember(Value = "Admin")]
            AdminEnum = 1
        }
}
