/*
 * Recipe Management Web Application API
 *
 * Recipe create/list/update/delete operations with allergen-based filtering.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Wemcy.RecipeApp.Backend.Api.Converters;

namespace Wemcy.RecipeApp.Backend.Api.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class UpdateFeaturedRecipeRequest : IEquatable<UpdateFeaturedRecipeRequest>
    {
        /// <summary>
        /// The unique identifier of the recipe to set as featured.
        /// </summary>
        /// <value>The unique identifier of the recipe to set as featured.</value>
        [Required]
        [DataMember(Name="recipeId", EmitDefaultValue=true)]
        public Guid RecipeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateFeaturedRecipeRequest {\n");
            sb.Append("  RecipeId: ").Append(RecipeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdateFeaturedRecipeRequest)obj);
        }

        /// <summary>
        /// Returns true if UpdateFeaturedRecipeRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateFeaturedRecipeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateFeaturedRecipeRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    RecipeId == other.RecipeId ||
                    
                    RecipeId.Equals(other.RecipeId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + RecipeId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpdateFeaturedRecipeRequest left, UpdateFeaturedRecipeRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdateFeaturedRecipeRequest left, UpdateFeaturedRecipeRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
