/*
 * Recipe Management Web Application API
 *
 * Recipe create/list/update/delete operations with allergen-based filtering.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Wemcy.RecipeApp.Backend.Api.Converters;

namespace Wemcy.RecipeApp.Backend.Api.Models
{ 
        /// <summary>
        /// Role to assign to the user (currently supported: \"Admin\")
        /// </summary>
        /// <value>Role to assign to the user (currently supported: \"Admin\")</value>
        [TypeConverter(typeof(CustomEnumConverter<UserRole>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum UserRole
        {
            
            /// <summary>
            /// Enum AdminEnum for Admin
            /// </summary>
            [EnumMember(Value = "Admin")]
            AdminEnum = 1
        }
}
