// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wemcy.RecipeApp.Backend.Database;

#nullable disable

namespace Wemcy.RecipeApp.Backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260228201618_Added-Ingredients")]
    partial class AddedIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergenRecipe", b =>
                {
                    b.Property<int>("AllergensType")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uuid");

                    b.HasKey("AllergensType", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("AllergenRecipe");
                });

            modelBuilder.Entity("Wemcy.RecipeApp.Backend.Model.Allergen", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Type");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Type = 1
                        },
                        new
                        {
                            Type = 2
                        },
                        new
                        {
                            Type = 3
                        },
                        new
                        {
                            Type = 4
                        },
                        new
                        {
                            Type = 5
                        },
                        new
                        {
                            Type = 6
                        },
                        new
                        {
                            Type = 7
                        },
                        new
                        {
                            Type = 8
                        },
                        new
                        {
                            Type = 9
                        },
                        new
                        {
                            Type = 10
                        },
                        new
                        {
                            Type = 11
                        },
                        new
                        {
                            Type = 12
                        },
                        new
                        {
                            Type = 13
                        },
                        new
                        {
                            Type = 14
                        });
                });

            modelBuilder.Entity("Wemcy.RecipeApp.Backend.Model.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Steps")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("AllergenRecipe", b =>
                {
                    b.HasOne("Wemcy.RecipeApp.Backend.Model.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergensType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wemcy.RecipeApp.Backend.Model.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wemcy.RecipeApp.Backend.Model.Recipe", b =>
                {
                    b.OwnsMany("Wemcy.RecipeApp.Backend.Model.Ingredient", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<string>("UnitOfMesurement")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RecipeId", "Id");

                            b1.ToTable("Ingredient");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
