/*
 * Recipe Management Web Application API
 *
 * Recipe create/list/update/delete operations with allergen-based filtering.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Wemcy.RecipeApp.Backend.Api.Attributes;
using Wemcy.RecipeApp.Backend.Api.Models;

namespace Wemcy.RecipeApp.Backend.Api.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class AuthApiController : ControllerBase
    {
        /// <summary>
        /// Login
        /// </summary>
        /// <param name="loginRequest"></param>
        /// <response code="200">Login successful; session cookie set</response>
        /// <response code="401">Invalid email address or password</response>
        [HttpPost]
        [Route("/auth/login")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(LoginResponse))]
        [ProducesResponseType(statusCode: 401, type: typeof(Login401Response))]
        public abstract Task<IActionResult> Login([FromBody] LoginRequest loginRequest);

        /// <summary>
        /// Logout
        /// </summary>
        /// <response code="204">Logout successful; cookie removed</response>
        /// <response code="401">No active session</response>
        [HttpPost]
        [Route("/auth/logout")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> Logout();

        /// <summary>
        /// User registration
        /// </summary>
        /// <param name="registerRequest"></param>
        /// <response code="200">Registration successful</response>
        /// <response code="400">Invalid request (e.g., email already in use, weak password)</response>
        [HttpPost]
        [Route("/auth/register")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(LoginResponse))]
        [ProducesResponseType(statusCode: 400, type: typeof(List<IdentityError>))]
        public abstract Task<IActionResult> Register([FromBody] RegisterRequest registerRequest);
    }
}
