/*
 * Receptkezelő webalkalmazás API
 *
 * Recepthozzáadás, -listázás, -szerkesztés, -törlés; allergén-alapú szűréssel.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Wemcy.RecipeApp.Backend.Api.Attributes;
using Wemcy.RecipeApp.Backend.Api.Models;

namespace Wemcy.RecipeApp.Backend.Api.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class AuthApiController : ControllerBase
    {
        /// <summary>
        /// Bejelentkezés
        /// </summary>
        /// <param name="loginRequest"></param>
        /// <response code="200">Sikeres bejelentkezés – munkamenet cookie beállítva</response>
        /// <response code="401">Hibás email cím vagy jelszó</response>
        [HttpPost]
        [Route("/auth/login")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(LoginResponse))]
        [ProducesResponseType(statusCode: 401, type: typeof(Login401Response))]
        public abstract Task<IActionResult> Login([FromBody] LoginRequest loginRequest);

        /// <summary>
        /// Kijelentkezés
        /// </summary>
        /// <response code="204">Sikeres kijelentkezés, cookie törlésre kerül</response>
        /// <response code="401">Nem volt aktív munkamenet</response>
        [HttpPost]
        [Route("/auth/logout")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        public abstract Task<IActionResult> Logout();

        /// <summary>
        /// Felhasználó regisztráció
        /// </summary>
        /// <param name="registerRequest"></param>
        /// <response code="200">Sikeres regisztráció</response>
        /// <response code="400">Érvénytelen kérés (pl. az email már foglalt, gyenge jelszó)</response>
        [HttpPost]
        [Route("/auth/register")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(LoginResponse))]
        [ProducesResponseType(statusCode: 400, type: typeof(List<IdentityError>))]
        public abstract Task<IActionResult> Register([FromBody] RegisterRequest registerRequest);
    }
}
