/*
 * Recipe Management Web Application API
 *
 * Recipe create/list/update/delete operations with allergen-based filtering.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Wemcy.RecipeApp.Backend.Api.Attributes;
using Wemcy.RecipeApp.Backend.Api.Models;

namespace Wemcy.RecipeApp.Backend.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class HealthApiController : ControllerBase
    { 
        /// <summary>
        /// Service health report
        /// </summary>
        /// <response code="200">Report is sent back</response>
        [HttpGet]
        [Route("/alive/")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(AliveReport))]
        public abstract Task<IActionResult> GetServiceReport();
    }
}
