/*
 * Recipe Management Web Application API
 *
 * Recipe create/list/update/delete operations with allergen-based filtering.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Wemcy.RecipeApp.Backend.Api.Attributes;
using Wemcy.RecipeApp.Backend.Api.Models;

namespace Wemcy.RecipeApp.Backend.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class IngredientsApiController : ControllerBase
    { 
        /// <summary>
        /// Create a new ingredient
        /// </summary>
        /// <param name="ingredientSuggestion"></param>
        /// <response code="201">Ingredient created successfully</response>
        /// <response code="400">Invalid ingredient data supplied</response>
        /// <response code="401">No active session</response>
        /// <response code="403">Not authorized to create ingredients</response>
        [HttpPost]
        [Route("/ingredients/")]
        [Authorize(Policy = "cookieAuth")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 201, type: typeof(Ingredient))]
        [ProducesResponseType(statusCode: 400, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> CreateIngredient([FromBody]IngredientSuggestion ingredientSuggestion);

        /// <summary>
        /// Delete an existing ingredient suggestion
        /// </summary>
        /// <param name="id">Unique identifier of the ingredient to delete (UUID)</param>
        /// <response code="204">Ingredient suggestion deleted successfully</response>
        /// <response code="401">No active session</response>
        /// <response code="403">Not authorized to delete ingredient suggestions</response>
        /// <response code="404">Ingredient suggestion not found</response>
        [HttpDelete]
        [Route("/ingredients/{id}")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> DeleteIngredient([FromRoute (Name = "id")][Required]Guid id);

        /// <summary>
        /// Get ingredient by ID
        /// </summary>
        /// <param name="id">Unique identifier of the ingredient to query (UUID)</param>
        /// <response code="200">Ingredient retrieved successfully</response>
        /// <response code="404">Ingredient not found</response>
        [HttpGet]
        [Route("/ingredients/{id}")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(Ingredient))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> GetIngredientById([FromRoute (Name = "id")][Required]Guid id);

        /// <summary>
        /// Search ingredients by name
        /// </summary>
        /// <param name="name">The name or part of the name to search for</param>
        /// <response code="200">List of ingredients matching the search criteria</response>
        [HttpGet]
        [Route("/ingredients/")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(List<IngredientSuggestion>))]
        public abstract Task<IActionResult> SearchIngredients([FromQuery (Name = "name")][Required()]string name);

        /// <summary>
        /// Update an existing ingredient suggestion
        /// </summary>
        /// <param name="id">Unique identifier of the ingredient suggestion to update (UUID)</param>
        /// <param name="ingredientSuggestion"></param>
        /// <response code="200">Ingredient suggestion updated successfully</response>
        /// <response code="400">Invalid ingredient suggestion data supplied</response>
        /// <response code="401">No active session</response>
        /// <response code="403">Not authorized to update ingredient suggestions</response>
        /// <response code="404">Ingredient suggestion not found</response>
        [HttpPut]
        [Route("/ingredients/{id}")]
        [Authorize(Policy = "cookieAuth")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(Ingredient))]
        [ProducesResponseType(statusCode: 400, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> UpdateIngredient([FromRoute (Name = "id")][Required]Guid id, [FromBody]IngredientSuggestion ingredientSuggestion);
    }
}
