/*
 * Recipe Management Web Application API
 *
 * Recipe create/list/update/delete operations with allergen-based filtering.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Wemcy.RecipeApp.Backend.Api.Attributes;
using Wemcy.RecipeApp.Backend.Api.Models;

namespace Wemcy.RecipeApp.Backend.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ProfileApiController : ControllerBase
    { 
        /// <summary>
        /// Add role to user by ID
        /// </summary>
        /// <param name="id">Unique identifier of the user to update (UUID)</param>
        /// <param name="addUserRoleByIdRequest"></param>
        /// <response code="204">User role added successfully</response>
        /// <response code="401">No active session</response>
        /// <response code="403">Not authorized to perform this operation (only admins can modify roles)</response>
        /// <response code="404">User not found</response>
        /// <response code="400">Invalid role provided</response>
        [HttpPost]
        [Route("/profile/{id}/roles")]
        [Authorize(Policy = "cookieAuth")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 400, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> AddUserRoleById([FromRoute (Name = "id")][Required]Guid id, [FromBody]AddUserRoleByIdRequest addUserRoleByIdRequest);

        /// <summary>
        /// Delete user by ID
        /// </summary>
        /// <param name="id">Unique identifier of the user to delete (UUID)</param>
        /// <response code="204">User deleted successfully</response>
        /// <response code="401">No active session</response>
        /// <response code="403">Not the owner of this user profile</response>
        /// <response code="404">User not found</response>
        [HttpDelete]
        [Route("/profile/{id}")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> DeleteProfileById([FromRoute (Name = "id")][Required]Guid id);

        /// <summary>
        /// Get the logged-in user profile
        /// </summary>
        /// <response code="200">Request successful</response>
        /// <response code="401">No active session</response>
        [HttpGet]
        [Route("/profile/me")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(Profile))]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> GetOwnProfile();

        /// <summary>
        /// Get the logged-in user profile image
        /// </summary>
        /// <param name="imageSize">Desired profile image size (e.g., \&quot;thumbnail\&quot;, \&quot;medium\&quot;, \&quot;large\&quot;)</param>
        /// <response code="200">Profile image retrieved successfully</response>
        /// <response code="401">No active session</response>
        [HttpGet]
        [Route("/profile/me/image")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(System.IO.Stream))]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> GetOwnProfileImage([FromQuery (Name = "imageSize")]ImageSize? imageSize);

        /// <summary>
        /// Get user profile by ID
        /// </summary>
        /// <param name="id">Unique identifier of the user to query (UUID)</param>
        /// <response code="200">User profile retrieved successfully</response>
        /// <response code="401">No active session</response>
        /// <response code="404">User not found</response>
        [HttpGet]
        [Route("/profile/{id}")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(Profile))]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> GetProfileById([FromRoute (Name = "id")][Required]Guid id);

        /// <summary>
        /// Get user profile image by ID
        /// </summary>
        /// <param name="id">Unique identifier of the user to query (UUID)</param>
        /// <param name="size">Desired image size (e.g., \&quot;thumbnail\&quot;, \&quot;medium\&quot;, \&quot;large\&quot;)</param>
        /// <response code="200">Profile image retrieved successfully</response>
        /// <response code="404">Profile image or user not found</response>
        [HttpGet]
        [Route("/profile/{id}/image")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(System.IO.Stream))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> GetProfileImageById([FromRoute (Name = "id")][Required]Guid id, [FromQuery (Name = "size")]ImageSize? size);

        /// <summary>
        /// Update the logged-in user profile
        /// </summary>
        /// <param name="displayName">The user&#39;s display name</param>
        /// <param name="password">New password for the user account</param>
        /// <param name="profileImage">The profile image file to upload.</param>
        /// <param name="email">The user&#39;s email address (used as username)</param>
        /// <response code="204">Update successful</response>
        /// <response code="401">No active session</response>
        [HttpPut]
        [Route("/profile/me")]
        [Authorize(Policy = "cookieAuth")]
        [Consumes("multipart/form-data")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> UpdateOwnProfile([FromForm (Name = "displayName")]string? displayName, [FromForm (Name = "password")] [MinLength(6)]string? password, IFormFile profileImage, [FromForm (Name = "email")]string? email);

        /// <summary>
        /// Update user profile by ID
        /// </summary>
        /// <param name="id">Unique identifier of the user to update (UUID)</param>
        /// <param name="displayName">The user&#39;s display name</param>
        /// <param name="password">New password for the user account</param>
        /// <param name="profileImage">The profile image file to upload.</param>
        /// <param name="email">The user&#39;s email address (used as username)</param>
        /// <response code="204">User profile updated successfully</response>
        /// <response code="401">No active session</response>
        /// <response code="403">Not the owner of this user profile</response>
        /// <response code="404">User not found</response>
        [HttpPut]
        [Route("/profile/{id}")]
        [Authorize(Policy = "cookieAuth")]
        [Consumes("multipart/form-data")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> UpdateProfileById([FromRoute (Name = "id")][Required]Guid id, [FromForm (Name = "displayName")]string? displayName, [FromForm (Name = "password")] [MinLength(6)]string? password, IFormFile profileImage, [FromForm (Name = "email")]string? email);
    }
}
