/*
 * Receptkezelő webalkalmazás API
 *
 * Recepthozzáadás, -listázás, -szerkesztés, -törlés; allergén-alapú szűréssel.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Wemcy.RecipeApp.Backend.Api.Attributes;
using Wemcy.RecipeApp.Backend.Api.Models;

namespace Wemcy.RecipeApp.Backend.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ProfileApiController : ControllerBase
    { 
        /// <summary>
        /// Felhasználó törlése ID alapján
        /// </summary>
        /// <param name="id">A törlendő felhasználó egyedi azonosítója (UUID)</param>
        /// <response code="204">Felhasználó sikeresen törölve</response>
        /// <response code="401">Nem volt aktív munkamenet</response>
        /// <response code="403">Nem a felhasználó tulajdonosa</response>
        /// <response code="404">Felhasználó nem található</response>
        [HttpDelete]
        [Route("/profile/{id}")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        public abstract Task<IActionResult> DeleteProfileById([FromRoute (Name = "id")][Required]Guid id);

        /// <summary>
        /// Bejelentkezett felhasználó adatainak lekérdezése
        /// </summary>
        /// <response code="200">Sikeres lekérdezés</response>
        /// <response code="401">Nem volt aktív munkamenet</response>
        [HttpGet]
        [Route("/profile/me")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(ProfileResponse))]
        public abstract Task<IActionResult> GetOwnProfile();

        /// <summary>
        /// Bejelentkezett felhasználó profilképének lekérdezése
        /// </summary>
        /// <response code="200">Profilkép sikeresen lekérdezve</response>
        /// <response code="401">Nem volt aktív munkamenet</response>
        [HttpGet]
        [Route("/profile/me/image")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(System.IO.Stream))]
        public abstract Task<IActionResult> GetOwnProfileImage();

        /// <summary>
        /// Felhasználó adatainak lekérdezése ID alapján
        /// </summary>
        /// <param name="id">A lekérdezendő felhasználó egyedi azonosítója (UUID)</param>
        /// <response code="200">Felhasználó adatai sikeresen lekérdezve</response>
        /// <response code="401">Nem volt aktív munkamenet</response>
        /// <response code="404">Felhasználó nem található</response>
        [HttpGet]
        [Route("/profile/{id}")]
        [Authorize(Policy = "cookieAuth")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(ProfileResponse))]
        public abstract Task<IActionResult> GetProfileById([FromRoute (Name = "id")][Required]Guid id);

        /// <summary>
        /// Felhasználó profilképének lekérdezése ID alapján
        /// </summary>
        /// <param name="id">A lekérdezendő felhasználó egyedi azonosítója (UUID)</param>
        /// <response code="200">Profilkép sikeresen lekérdezve</response>
        /// <response code="404">Profilkép vagy felhasználó nem található</response>
        [HttpGet]
        [Route("/profile/{id}/image")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(System.IO.Stream))]
        public abstract Task<IActionResult> GetProfileImageById([FromRoute (Name = "id")][Required]Guid id);

        /// <summary>
        /// Bejelentkezett felhasználó adatainak frissítése
        /// </summary>
        /// <param name="displayName">The user&#39;s display name</param>
        /// <param name="password">Password</param>
        /// <param name="profileImage">The profile image file to upload.</param>
        /// <response code="204">Sikeres frissítés</response>
        /// <response code="401">Nem volt aktív munkamenet</response>
        [HttpPut]
        [Route("/profile/me")]
        [Authorize(Policy = "cookieAuth")]
        [Consumes("multipart/form-data")]
        [ValidateModelState]
        public abstract Task<IActionResult> UpdateOwnProfile([FromForm (Name = "displayName")]string? displayName, [FromForm (Name = "password")] [MinLength(6)]string? password, IFormFile profileImage);

        /// <summary>
        /// Felhasználó adatainak frissítése ID alapján
        /// </summary>
        /// <param name="id">A frissítendő felhasználó egyedi azonosítója (UUID)</param>
        /// <param name="displayName">The user&#39;s display name</param>
        /// <param name="password">Password</param>
        /// <param name="profileImage">The profile image file to upload.</param>
        /// <response code="204">Felhasználó adatai sikeresen frissítve</response>
        /// <response code="401">Nem volt aktív munkamenet</response>
        /// <response code="403">Nem a felhasználó tulajdonosa</response>
        /// <response code="404">Felhasználó nem található</response>
        [HttpPut]
        [Route("/profile/{id}")]
        [Authorize(Policy = "cookieAuth")]
        [Consumes("multipart/form-data")]
        [ValidateModelState]
        public abstract Task<IActionResult> UpdateProfileById([FromRoute (Name = "id")][Required]Guid id, [FromForm (Name = "displayName")]string? displayName, [FromForm (Name = "password")] [MinLength(6)]string? password, IFormFile profileImage);
    }
}
