/*
 * Receptkezelő webalkalmazás API
 *
 * Recepthozzáadás, -listázás, -szerkesztés, -törlés; allergén-alapú szűréssel.
 *
 * The version of the OpenAPI document: v0.1.0-dev
 * Contact: mzsoltsandor@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Wemcy.RecipeApp.Backend.Api.Attributes;
using Wemcy.RecipeApp.Backend.Api.Models;

namespace Wemcy.RecipeApp.Backend.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class RecipesApiController : ControllerBase
    { 
        /// <summary>
        /// Új recept létrehozása
        /// </summary>
        /// <param name="createRecipeDTO"></param>
        /// <response code="201">Recipe created successfully</response>
        [HttpPost]
        [Route("/recipes/")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 201, type: typeof(ReadRecipeDTO))]
        public abstract IActionResult CreateRecipe([FromBody]CreateRecipeDTO createRecipeDTO);

        /// <summary>
        /// Receptek listázása
        /// </summary>
        /// <response code="200">Receptek</response>
        [HttpGet]
        [Route("/recipes/")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(List<ReadRecipeDTO>))]
        public abstract IActionResult ListRecipes();
    }
}
